name: Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install dependencies
        run: npm ci

      - name: Run lint check
        run: npm run lint-check

      - name: Run formatting check
        run: npm run prettier-check
